version: '3.2'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - /app
    ports:
      - 5001:80

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /client/node_modules
      - ./client:/app/client
    ports:
      - 4200:4200
    depends_on:
      - server